#+ endpoint: http://localhost:3030/saam/query
#+ summary: Get Artist name, birth and death date
#+ tags: 
#+   - metadata 

PREFIX artist: <https://americanart.si.edu/artist/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX schema: <http://schema.org/>
SELECT ?artist_name ?artist_date_of_birth ?artist_date_of_death
WHERE {
  ?artist rdf:type schema:Artist ;
          schema:artistName ?artist_name ;
          schema:birthDate ?artist_date_of_birth .
  OPTIONAL {?artist schema:deathDate ?artist_date_of_death }
}
ORDER BY ?artist_name
LIMIT 10
