PREFIX artist: <https://americanart.si.edu/artist/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX schema: <http://schema.org/>
SELECT ?artist_name COUNT(?artwork)
WHERE {
  ?artist rdf:type schema:Artist ;
          schema:artistName ?artist_name .
  ?artwork rdf:type schema:Artwork ;
           schema:artworkCreator ?artist .
}
GROUP BY ?artist_name
ORDER BY DESC(COUNT(?artwork))
LIMIT 5