#+ endpoint: http://192.168.0.1:3030/saam/update
#+ method: POST
#+ summary: Create a new artist entry

PREFIX artist: <https://americanart.si.edu/artist/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX schema: <http://schema.org/>

INSERT DATA
{{
  artist:Anuj_Doiphode rdf:type schema:Artist;
                       schema:artistName "ABCD".
}}
