#+ endpoint: http://192.168.0.1:3030/saam/query
#+ method: POST
#+ summary: Get Newly created artist entry

PREFIX artist: <https://americanart.si.edu/artist/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX schema: <http://schema.org/>

SELECT *
FROM <http://192.168.0.1:3030/saam>
WHERE {
  ?s ?p ?o
}
